version: '3'

services:

  lastbin:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lastbin-dev
    volumes:
      - ./server.lua:/lastbin/server.lua:ro
      - ./tmpl:/lastbin/tmpl:ro
      - ./www:/lastbin/www:ro
      - ./libs/mimes.lua:/lastbin/libs/mimes.lua:ro
      - ./libs/template.lua:/lastbin/libs/template.lua:ro
    ports:
      - "42424:42424"
